export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headLine:'Unlimited Transaction with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel:'Get Started',
    imgStart: false,
    img: '/images/svg1.svg',
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'UNLIMITED ACCESS',
    headLine:'Login to your account at anytime',
    description: 'We have you covered, no matter where you are. to send unlimited transactions without getting charged any fees.',
    buttonLabel:'Learn more',
    imgStart: true,
    img: '/images/svg1.svg',
    alt: 'piggyBank',
    dark: false,
    primary: false,
    darkText: true,
}
export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Join our team',
    headLine:'Creating an account is extremely easy',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel:'Start Now',
    imgStart: false,
    img: '/images/svg1.svg',
    alt: 'paper',
    dark: false,
    primary: false,
    darkText: true,
}
